"""autoresearch config init — 生成 config/config.yaml 模板 (CFG-INIT-01..03).

设计 (D-02/D-03/D-06):
- 复制 config/config.example.yaml 到目标路径
- 插入 "# Generated by autoresearch config init at <ISO time>" header
- 保留所有原注释 (走文件级 shutil.copyfile, 不走 yaml 解析)
- 已存在 → exit 3 (除非 --force)
- --force 覆盖, stderr 写 "⚠ 覆盖现有 config/config.yaml"
"""
from __future__ import annotations

import datetime
import shutil
import sys
from pathlib import Path

import click

from ._common import TEMPLATE_PATH, resolve_config_path


def _generate_header() -> str:
    """首行注释: 标记 generated + 下一步建议."""
    ts = datetime.datetime.now(tz=datetime.timezone.utc).isoformat(timespec="seconds")
    return (
        f"# Generated by autoresearch config init at {ts}\n"
        f"# 编辑完跑: autoresearch config validate\n"
        f"# 敏感字段不要用明文密码, 改 <env:VAR> 或 <keyring:NAME> 占位符\n"
        f"\n"
    )


def run_init(
    *, force: bool = False, config: str | None = None, lang: str = "zh"
) -> int:
    """Init 子命令主入口.

    Returns:
        exit code: 0 = 写成功, 3 = 已存在 (不覆盖), 2 = 模板缺失
    """
    target = resolve_config_path(config)

    if not TEMPLATE_PATH.exists():
        msg = (
            f"错误: 模板文件不存在 {TEMPLATE_PATH} (应在仓根随仓走)"
            if lang == "zh"
            else f"Error: template not found at {TEMPLATE_PATH}"
        )
        print(msg, file=sys.stderr)
        return 2

    if target.exists() and not force:
        msg = (
            f"配置已存在: {target} (不会覆盖). 用 --force 强制覆盖, "
            f"或用 --config <path> 写到别的路径."
            if lang == "zh"
            else f"Config already exists: {target} (not overwriting). Use --force or --config."
        )
        print(msg, file=sys.stderr)
        return 3

    if target.exists() and force:
        warn = f"⚠ 覆盖现有 {target} (--force)"
        print(warn, file=sys.stderr)

    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(TEMPLATE_PATH, target)
    original = target.read_text(encoding="utf-8")
    target.write_text(_generate_header() + original, encoding="utf-8")

    if lang == "zh":
        print(f"✅ 已生成: {target}")
        print(f"   跑: autoresearch config validate  # 校验")
        print(f"   跑: autoresearch config show      # 查看 (敏感字段脱敏)")
    else:
        print(f"✅ Generated: {target}")
        print(f"   Next: autoresearch config validate")
    return 0
