"""Tests for autoresearch config init (CFG-INIT-01..03)."""
import os
import pytest
from click.testing import CliRunner

from autoresearch.cli import main
import autoresearch.config.init as init_mod


def test_init_creates_config_yaml_with_chinese_comments(tmp_path, monkeypatch):
    """CFG-INIT-01 + CFG-INIT-02: 生成的 yaml 含中文注释."""
    monkeypatch.chdir(tmp_path)
    runner = CliRunner()
    result = runner.invoke(main, ["config", "init"])
    assert result.exit_code == 0
    p = tmp_path / "config" / "config.yaml"
    assert p.exists()
    content = p.read_text(encoding="utf-8")
    assert any("\u4e00" <= c <= "\u9fff" for c in content), "no Chinese chars"
    assert "Generated by autoresearch config init" in content


def test_init_exits_3_when_config_exists(tmp_path, monkeypatch):
    """CFG-INIT-03: 重复 init 返 exit 3."""
    monkeypatch.chdir(tmp_path)
    runner = CliRunner()
    r1 = runner.invoke(main, ["config", "init"])
    assert r1.exit_code == 0
    r2 = runner.invoke(main, ["config", "init"])
    assert r2.exit_code == 3
    combined = (r2.output or "") + (r2.stderr or "")
    assert "--force" in combined or "force" in combined.lower()


def test_init_force_overwrites_existing(tmp_path, monkeypatch):
    """CFG-INIT-03: --force 覆盖."""
    monkeypatch.chdir(tmp_path)
    runner = CliRunner()
    r1 = runner.invoke(main, ["config", "init"])
    assert r1.exit_code == 0
    p = tmp_path / "config" / "config.yaml"
    with open(p, "a", encoding="utf-8") as f:
        f.write("# user-added comment\n")
    r2 = runner.invoke(main, ["config", "init", "--force"])
    assert r2.exit_code == 0
    content = p.read_text(encoding="utf-8")
    assert "user-added comment" not in content


def test_init_with_custom_config_path(tmp_path, monkeypatch):
    """D-06: --config 写到别的路径."""
    monkeypatch.chdir(tmp_path)
    runner = CliRunner()
    result = runner.invoke(
        main, ["config", "init", "--config", "my/custom/config.yaml"]
    )
    assert result.exit_code == 0
    assert (tmp_path / "my" / "custom" / "config.yaml").exists()


def test_init_template_missing_returns_2(tmp_path, monkeypatch):
    """DI-01: 模板文件不存在 → exit 2 + 中文错误."""
    monkeypatch.setattr(
        init_mod, "TEMPLATE_PATH", tmp_path / "nonexistent.yaml"
    )
    monkeypatch.chdir(tmp_path)
    runner = CliRunner()
    result = runner.invoke(main, ["config", "init"])
    assert result.exit_code == 2
    combined = (result.output or "") + (result.stderr or "")
    assert "模板" in combined or "template" in combined.lower()
